### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by ocdtrekkie** [babybuddy/babybuddy-sandstorm#2]
It is probably somewhat infrequent that a new Sandstorm user is hoping to start using BabyBuddy, but as unexpected to me as it is... I am expecting to need this app in approximately two months! I am not sure how significant the updates are from 1.4 to 1.9, or if there's any significant bitrot in updating the Sandstorm package, but I was curious if that would be possible.

**Comment by cdubz** [comment]
Congrats! I’ll take a look here soon. There are have been a number of decent improvements in recent versions.

**Comment by cdubz** [comment]
Well first hurdle... it seems, of course, I have lost the key material for my app ID :grimacing:

If I generate a new key and submit the app again am I going to end with a duplicate app and/or not be able to submit under the same app title or something?

**Comment by ocdtrekkie** [comment]
So yes, that would generally be an issue, but we have a system for that. You would submit a PR for https://github.com/sandstorm-io/sandstorm/blob/0d53a6646ab99c2cd4e54d2fc2d04d69f1e18366/src/sandstorm/appid-replacements.capnp which, once merged, would tell both the app market and Sandstorm that a given app with a new key is the same, and permit updates from one to the other.

**Comment by cdubz** [comment]
Good news -- I found the key materials on an old computer. However, new problem, I have imported the proper secrets on my new computer but I can't seem to get vagrant to recognize them? Here's the output when I try to test for the key --

```
chris@crushinator:~/PycharmProjects/babybuddy-sandstorm$ vagrant-spk getkey 7yu31zwuv5f0aeg0749hvtrfz92g5ccq4mf21nvmspxwjs61duwh
Calling 'vagrant' 'ssh' '-c' 'spk getkey --keyring=/host-dot-sandstorm/sandstorm-keyring 7yu31zwuv5f0aeg0749hvtrfz92g5ccq4mf21nvmspxwjs61duwh' '--' '-T' in ~/PycharmProjects/babybuddy-sandstorm/.sandstorm
7yu31zwuv5f0aeg0749hvtrfz92g5ccq4mf21nvmspxwjs61duwh: key not found in keyring
Command failed with a non-zero exit status (1).
```

I tried destroying and rebuilding the vm but maybe that's not relevant anyway? I'm a little unclear on how this process is supposed to work...

**Comment by cdubz** [comment]
Ah figured it out from the [Raw packing guide documentation](https://docs.sandstorm.io/en/latest/developing/raw-packaging-guide/#keyrings) finally! Now I have everything set up (and backed up!) properly... 🎉

**Comment by cdubz** [comment]
Alright I posted and submitted v3 based on Baby Buddy v1.5.0 just to get things tested. Will do a v4 release soon with the latest version of Baby Buddy.

**Comment by ocdtrekkie** [comment]
I need to clean the update approval queue up, but I created a BabyBuddy 1.4 instance, and updated it to 1.5 from the experimental market, and that all looks good!

**Comment by cdubz** [comment]
Great! I'm going to delay at least a few days here anyway because I think its about time for a new point release of Baby Buddy. After that I'll work on getting the Sandstorm build up to date on 1.9.x. I think there _may_ be some Sandstorm specific hitches between 1.5.0 and 1.9.x.

**Comment by cdubz** [comment]
:wave: @ocdtrekkie [v4](https://github.com/babybuddy/babybuddy-sandstorm/releases/tag/v4) based on the latest version of Baby Buddy has been submitted for publishing!

**Comment by ocdtrekkie** [comment]
Approved to the app market.
